services:
  solid_pod_1:
    image: solidproject/community-server:latest
    container_name: solid_pod_1
    ports:
      - "3001:3000" # Exposes pod1 on host port 3001
    volumes:
      - ./solid_pods/solid_pod_1/data:/app/data
    environment:
      - DATA_PATH=/app/data
    restart: always
  solid_pod_2:
    image: solidproject/community-server:latest
    container_name: solid_pod_2
    ports:
      - "3002:3000" # Exposes pod2 on host port 3002
    volumes:
      - ./solid_pods/solid_pod_2/data:/app/data
    environment:
      - DATA_PATH=/app/data
    restart: always

  solid_pod_3:
    image: solidproject/community-server:latest
    container_name: solid_pod_3
    ports:
      - "3003:3000" # Exposes pod3 on host port 3003
    volumes:
      - ./solid_pods/solid_pod_3/data:/app/data
    environment:
      - DATA_PATH=/app/data
    restart: always

  solid_pod_4:
    image: solidproject/community-server:latest
    container_name: solid_pod_4
    ports:
      - "3004:3000" # Exposes pod4 on host port 3004
    volumes:
      - ./solid_pods/solid_pod_4/data:/app/data
    environment:
      - DATA_PATH=/app/data
    restart: always

  solid_pod_5:
    image: solidproject/community-server:latest
    container_name: solid_pod_5
    ports:
      - "3005:3000" # Exposes pod5 on host port 3005
    volumes:
      - ./solid_pods/solid_pod_5/data:/app/data
    environment:
      - DATA_PATH=/app/data
    restart: always

# Communica CI Service: Runs Communica for SPARQL federation queries
  communica:
    image: comunica/query-sparql:latest
    container_name: communica
    ports:
      - "4000:4000"
    volumes:
      - ./communica_config:/app/config
    command: >
      bash -c "communica-sparql -c /app/config/federation-config.json"
    depends_on:
      - solid_pod_1
      - solid_pod_2
      - solid_pod_3
      - solid_pod_4
      - solid_pod_5

  # Python Application Service: Sends SPARQL queries to the pods
  python_app:
    build: ./python_app
    container_name: python_app
    volumes:
      - ./python_app:/app
    ports:
      - "5000:5000"
    depends_on:
      - solid_pod_1
      - solid_pod_2
      - solid_pod_3
      - solid_pod_4
      - solid_pod_5
      - communica